apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pv
spec:
  selector:
    matchLabels:
      app: pv
  template:
    metadata:
      labels:
        app: pv
    spec:
      containers:
      - name: pv
        image: nginx:latest       
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: zabbix-mysql-pvc
