apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zabbix-mysql
spec:
  selector:
    matchLabels:
      app: zabbix-mysql
  template:
    metadata:
      labels:
        app: zabbix-mysql
    spec:
      containers:
      - name: zabbix-mysql
        image: mysql:5.7
        args:
          # - '--character-set-server=utf8mb4'
          - '--character-set-server=utf8'
          # - '--collation-server=utf8mb4_unicode_ci'
          - '--collation-server=utf8_bin'
          - '--default-authentication-plugin=mysql_native_password'
        env:
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix          
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql/ 
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: zabbix-mysql-pvc
